name: Format check

on: [push, pull_request]

jobs:
  check-main:
    if: ${{ github.event_name == 'push' }}
    name: Check all files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check file's formatting
      run: python tools/check_format.py

  check-pr:
    if: ${{ github.event_name != 'push' }}
    name: Check modified files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check file's formatting
      run: python tools/check_format.py --verbose --compare-to origin/develop/2.1.0
